### PR TITLE
Users are able to join a random game or challenge an opponent directly

### PR DESCRIPTION
**Pull request by tomoliv30**
Pong component can react to a target and roomId hook that make it join a game automatically, otherwise it displays a menu with possibility to join a game.
When clicking 'join game' it emits a 'joinGame' event through a websocket, and displays a loader until it receives a start event.
On the backend, a game is an object which is added to a global 'State' wrapper object. Each key in this object is the roomId, and the mapped value is the said game with info about each players and the actual game state that will be emitted to the Pong component.
The game gateway also stores roomIds in two arrays: public games and private games. Public games acts like a FIFO queue and that's how global match making is done: getting the first element in the queue, adding playerTwo, emit back the id, an 'init' event and broadcasting the state to everyone in the room.
For private rooms, you either call challenge friend with no roomId, which means you create a game and add it to the private array, or you have a roomId which is used as a key to access the room.
When you create a game, the gateway makes use of friendsGateway to find the targeted user and send them an event containing the roomId.
When receiving that event, a popup will show alerting you another user wants to play and upon clicking will set the target/roomId state contained in that event. Then the Pong component will react to that change, and will request to join a game with that id.
Following the matching process mentioned above, the game will start.

I made it so you can challenge anyone, but we can narrow it to friends. I tried to manage most use-cases, but we might find some things to fix. I struggled a bit with useEffects and its dependencies warnings, hence some parts of the code that look a bit intense, might refactor when I have a fresh mind.
Integrates #75 to prevent leaks and make use of the popup in the chat.

### CODE REVIEW

**Review by novan-ve — APPROVED** [review]
Works great, didn't find any bugs

**Review by borispeeters — APPROVED** [review]
Same here, looks and functions great!

**Review by tuan9999 — APPROVED** [review]
Looks great! one thing is when I was signed out and I tried to sign in with intra on the play button in the pong tab that didn't do anything.

**Comment by tomoliv30** [comment]
> Looks great! one thing is when I was signed out and I tried to sign in with intra on the play button in the pong tab that didn't do anything.

Yes, that was just a template to adapt to the new game styling, this is for another PR

**Pull request merged**
