### PR TITLE
Game custo

### PR DESCRIPTION
**Pull request by tomoliv30**
You can set difficulty, background color, player color, when challenging a user.
integrates #94

### CODE REVIEW

**Review by borispeeters — APPROVED** [review]
works for me, the actual speeds had extreme values I used for testing so I changed them to more reasonable values

**Comment by tomoliv30** [comment]
> works for me, the actual speeds had extreme values I used for testing so I changed them to more reasonable values

yep was thinking the same!

**Review by novan-ve — APPROVED** [review]
Looks amazing!

**Review by tuan9999 — APPROVED** [review]
looks good

**Pull request merged**
