### PR TITLE
New user redirect

### PR DESCRIPTION
**Pull request by borispeeters**
When a new user is created they are redirected to the settings page, when an existing user logs in with intra they are redirected to the home page.

### CODE REVIEW

**Comment by tuan9999** [comment]
yo bro how would I test this, tried creating a new user in the db and then logging in with that but that didn't work?

**Comment by borispeeters** [comment]
> yo bro how would I test this, tried creating a new user in the db and then logging in with that but that didn't work?

ye it only works when logging in with your intra account. If you delete your intra account through pgadmin then click 'log in via intra', it should redirect to the settings page.

**Comment by tomoliv30** [comment]
> > yo bro how would I test this, tried creating a new user in the db and then logging in with that but that didn't work?
> 
> ye it only works when logging in with your intra account. If you delete your intra account through pgadmin then click 'log in via intra', it should redirect to the settings page.

Actually it will redirect to the main branch deployment url if you don't change APP_URL manually in heroku, since every review app has a random URL. I just changed it to the review app url and rebuilding right now

**Review by tomoliv30 — APPROVED** [review]
I commited small changes related to using APP_URL instead of '/'. I tested on both local environments and it works, should work on master if APP_URL is set to the deploy url

**Comment by tuan9999** [comment]
> > yo bro how would I test this, tried creating a new user in the db and then logging in with that but that didn't work?
> 
> ye it only works when logging in with your intra account. If you delete your intra account through pgadmin then click 'log in via intra', it should redirect to the settings page.

Ah got it thanks man, but now when I log in with intra it's giving me an error: "{"statusCode":400,"message":"Failed to save","error":"Bad Request"}" have you come across this issue before?

**Review by novan-ve — APPROVED** [review]
Tried it on a clean build with a cleared postgres directory and it works for me.

**Review by tuan9999 — APPROVED** [review]
nvm haha did a clean build and works for me as well!

**Pull request merged**
